openapi: 3.0.3
info:
  title: API BCI - challenge
  description: API para registro de usuarios
  version: 1.0.0
servers:
  - url: http://localhost:9090/api/v1
paths:
  /sign_up:
    post:
      summary: Agregar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponseDTO'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
          example: david
        email:
          type: string
          example: dcusi@loballogic.com
        password:
          type: string
          example: '12345'
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneDTO'

    PhoneDTO:
      type: object
      properties:
        number:
          type: integer
        cityCode:
          type: integer
        countryCode:
          type: string

    RegisterResponseDTO:
      type: object
      properties:
        id:
          type: string
          example: "ac4628b5-18d7-4646-8e82-1b3d43eb1523"
        created:
          type: string
          format: date-time
          example: "2024-02-27T11:44:07Z"
        modified:
          type: string
          format: date-time
          example: "2024-02-27T11:44:07Z"
        lastLogin:
          type: string
          format: date-time
          example: "2024-02-27T11:44:07Z"
        token:
          type: string
          example: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYXZpZCIsImlhdCI"
        isActive:
          type: boolean
          example: true

    ErrorDTO:
      type: object
      properties:
        codigo:
          type: integer
          format: int32
          example: 500
        mensaje:
          type: string
          example: "El email existe"
        timestamp:
          type: string
          format: date-time
          example: "2024-02-27T11:45:52.708+00:00"

